apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.dep.name }}
  namespace: perf-platform
  labels:
    app.kubernetes.io/name: {{ .Values.dep.name }}

spec:
  replicas: {{ .Values.slave.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.dep.name }}

  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.dep.name }}

    spec:
      containers:
      - name: distributed-jmeter-slave
        image: "{{ .Values.slave.image }}:{{ .Values.slave.tag }}"
        imagePullPolicy: {{ .Values.slave.pullPolicy }}
        args: ["server"]
        command:
        - /bin/sh
        - -c
        - |
          echo "Starting Container";
          jmeter -v;
          while true
            do 
              sleep 30; 
            done
          
        env:
        - name: HEAP
          value: "-Xms{{ .Values.slave.heap.xms1.memory }} -Xmx{{ .Values.slave.heap.xms2.memory }}"
        
        ports:
          - containerPort: 50000
          - containerPort: 1099
        
        resources:
          requests:
            memory: "{{ .Values.slave.res.req.mem }}"
            cpu: "{{ .Values.slave.res.req.cpu }}"
          limits:
            memory: "{{ .Values.slave.res.lim.mem }}"
            cpu: "{{ .Values.slave.res.lim.cpu }}"