apiVersion: v1
kind: Service
metadata:
  namespace: perf-platform
  name: {{ .Values.dep.name }}-server
  
spec:
  clusterIP: None
  ports:
    - port: 50000
      protocol: TCP
      name: tcp-50000
    - port: 1099
      protocol: TCP
      name: tcp-1099
  selector:
    jmeter-mode: "server"