apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.dep.name }}-server
  labels:
    app.kubernetes.io/name: {{ .Values.dep.name }}
spec:
  clusterIP: None
  ports:
    - port: 50000
      protocol: TCP
      name: tcp-50000
    - port: 1099
      protocol: TCP
      name: tcp-1099
  selector:
    app.kubernetes.io/name: {{ .Values.dep.name }}